language: node_js
os:
  # - linux
  - windows
node_js:
  # - "8"
  - "10"
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
cache:
  directories:
    - "$(npm root -g)"
env:
  global:
    - CXX=clang++-5.0
    - CC=clang-5.0
    - _FORCE_LOGS=1
install:
  - npm install
  - npm list -g opencv4nodejs --depth=0 || npm i -g opencv4nodejs
  - npm install --no-save mjpeg-consumer
script:
  # - npm run test
  # - npm run e2e-test
  - npm ls -g opencv4nodejs -j
  - ls -la "C:\ProgramData\nvs\node\10.15.2\x64\node_modules\opencv4nodejs"
  - _FORCE_LOGS=1 npm run e2e-test
after_success:
  - npm run coverage
