language: node_js
os:
  # - linux
  - windows
node_js:
  # - "8"
  - "10"
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
env:
  global:
    - CXX=clang++-5.0
    - CC=clang-5.0
    - _FORCE_LOGS=1
install:
  - npm install
  - |
    printf "while [ true ]; do\nsleep 30\necho 'Building OpenCV'\ndone" > ping.sh
    bash ping.sh &
    echo $! > ping.pid
    npm i -g opencv4nodejs
    kill `cat ping.pid`
  - npm install --no-save mjpeg-consumer
script:
  - npm run test
  - npm run e2e-test
after_success:
  - npm run coverage
