language: node_js
node_js:
  - "8"
  - "10"
os:
  - linux
  - windows
cache:
  directories:
    - "$(npm root -g)"
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
env:
  global:
    - CXX=clang++-5.0
    - CC=clang-5.0
install:
  - npm install
  - npm list -g opencv4nodejs --depth=0 || npm i opencv4nodejs
  - npm install --no-save mjpeg-consumer
script:
  - npm run test
  - npm run e2e-test
after_success:
  - npm run coverage
